contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/mihonapp/mihon/issues/new/choose
    about: Issues and requests about the app itself should be opened in the Mihon repository instead
  - name: ğŸ“¦ Extensions
    url: https://mihon.app/extensions
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Website
    url: https://mihon.app/help/
    about: Guides, troubleshooting, and answers to common questions
